ALTER TABLE places
ADD COLUMN IF NOT EXISTS external_place_id VARCHAR(255) UNIQUE;

ALTER TABLE places
ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;

ALTER TABLE places
ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

ALTER TABLE places
ADD COLUMN IF NOT EXISTS price_level INT;

ALTER TABLE places
ADD COLUMN IF NOT EXISTS open_now BOOLEAN;

ALTER TABLE places
ADD COLUMN IF NOT EXISTS photo_url TEXT;

ALTER TABLE places
ADD COLUMN IF NOT EXISTS contact_phone VARCHAR(255);

ALTER TABLE places
ADD COLUMN IF NOT EXISTS primary_type VARCHAR(255);
