CREATE TABLE IF NOT EXISTS temporary_place_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id BIGINT NOT NULL REFERENCES places(id) ON DELETE CASCADE,
    external_place_id VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    address VARCHAR(500) NOT NULL,
    rating DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    price_level INTEGER,
    open_now BOOLEAN,
    photo_url TEXT,
    contact_phone VARCHAR(100),
    primary_type VARCHAR(100),
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_temporary_place_cache_place_id
ON temporary_place_cache(place_id);

CREATE INDEX IF NOT EXISTS idx_temporary_place_cache_expires_at
ON temporary_place_cache(expires_at);
